accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.signup_view, name = 'signup'),
    path('login', views.login_view, name = 'login'),
    
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('' , views.articles_list, name="list"),
    #path('<slug>' , views.articles_detail, name="detail"),
    
]

articles2/urls.py
from django.urls import path
from . import views

app_name = "articles2"
urlpatterns = [
    path('' , views.articles_list, name="listt"),
    #path('<slug>' , views.articles_detail, name="detail"),
    
]

articles3/urls.py
from django.urls import path
from . import views

app_name = "articles3"
urlpatterns = [
    path('' , views.articles_list, name="listtt"),
    #path('<slug>' , views.articles_detail, name="detail"),
    
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
# from .views import nav_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/' , views.about),
    path('' , views.home, name='home'),
    path('articles/' , include('articles.urls')),
    path('accounts/' , include('accounts.urls')),
    path('articles2/' , include('articles2.urls')),
    path('articles3/' , include('articles3.urls')),
    path('index/' , include('index.urls')),
    # path('accounts/', nav_view, name = 'template1'),
     
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"
urlpatterns = [
    path('' , views.articles_list, name="ind"),
    #path('<slug>' , views.articles_detail, name="detail"),
    
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg',blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body

articles2/models.py
from django.db import models

# Create your models here.
class Article2(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg',blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body

articles3/models.py
from django.db import models

# Create your models here.
class Article3(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg',blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body

index/models.py
from django.db import models

# Create your models here.
class Indexx(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg',blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            #login
            return redirect('articles:list')
    else:
        form = UserCreationForm()
        
    return render(request, 'accounts/signup.html' , {'form':form})



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login user
            user = form.get_user()
            login(request, user)
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html' , {'form':form})

# def nav_view(request):
#     # return response
#     return render(request, "signup.html")

articles/views.py
from django.shortcuts import render
from . import models 


# Create your views here.
def articles_list(request):
    articles = models.Article.objects.all().order_by('date')

    args = {'articles':articles}
    return render(request, 'articles/articleslist.html' , args)

articles2/views.py
from django.shortcuts import render
from . import models 


# Create your views here.
def articles_list(request):
    articles = models.Article2.objects.all().order_by('date')

    args = {'articles2':articles}
    return render(request, 'articles2/babol.html' , args)

articles3/views.py
from django.shortcuts import render
from . import models 


# Create your views here.
def articles_list(request):
    articles = models.Article3.objects.all().order_by('date')

    args = {'articles3':articles}
    return render(request, 'articles3/sari.html' , args)

djangoproject/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse


def about(request):
    #return HttpResponse('hi there! Im hello World!')
    return render(request , 'about.html')


def home(request):
    #return HttpResponse('Home')
    return render(request , 'Home.html')


# def nav_view(request):
#     # return response
#     return render(request, "signup.html")

index/views.py
from django.shortcuts import render
from . import models 


# Create your views here.
def articles_list(request):
    articles = models.Indexx.objects.all().order_by('date')

    args = {'index':articles}
    return render(request, 'index/index.html' , args)

articles/templates/articles/articleslist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>مازندران</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        
        <link rel="stylesheet" href="{% static 'style.css' %}">
        
	</head>

	<body>
        
        
        <nav class="navbar navbar-expand-md">
            <a class="navbar-brand" href="{%url 'accounts:login'%}" target="_blank">ورود</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'home'%}" target="_blank">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#A1">درباره ما</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:signup'%}" target="_blank">عضویت</a>
                    </li>
                </ul>
            </div>
        </nav>


        <header class="page-header header container-fluid">
            <div class="description">
                
                <h3>شهرستان زیبای آمل</h3>
                <p>آمل از شهرهای توریستی استان مازندران است که در فاصله نزدیکی از کوه دماوند واقع شده و دارای طبیعتی بکر و زیبا می باشد. هر ساله افراد زیادی از داخل و خارج کشور برای گشت و گذار در میان جاهای دیدنی  آمل راهی این شهر می شوند و  از همین رو از شهرهای توریستی استان مازندران به شمار می رود. از آنجایی که این شهر در نزدیکی های تهران قرار دارد، افراد زیادی از پایتخت را از مسیر جاده هراز به سوی خود دعوت می کند. آمل از کهن ترین شهرهای شمالی ایران بوده که به عنوان مرکز صنعتی و فرهنگی استان مازندران شناخته می شود.

                </p>
            </div>
        </header>

        {% for article in articles %}

        <div class="container featuresamol">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <h3 class="featureamol-title">{{article.title}}</h3>
                    <img src="{{article.image.url}}" class="img-fluid">
                    
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <br>
                    <br>
                    <p>{{article.snippet}}</p>
                    
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <div class="container">
            <a class="like"><i class="fa fa-thumbs-o-up"></i>  
                پسندیدم <input class="qty1" name="qty1" readonly="readonly" type="text" value="0" />
            </a>
            <a class="dislike"><i class="fa fa-thumbs-o-down"></i> 
                نپسندیدم <input class="qty2"  name="qty2" readonly="readonly" type="text" value="0" />
            </a>
        </div><br>
        
        {% endfor %}


        <div class="forms">
            <h4>نظر خود را راجع به این جاذبه ها ثبت کنید</h4>
            <form>
                <div class="form-group">
                  <label for="uname">نام :</label>
                  <input type="text" class="form-control" id="uname" placeholder="نام">
                </div>
    
                <div class="form-group">
                  <label for="exampleInputEmail1">ایمیل :</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل">
                </div>

                <div class="nform-group">
                    <label for="uname">نظر :</label>
                    <input type="text" class="form-control" id="uname" placeholder="نظر">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">ثبت نظر</button>
              </form><br>
        </div>

        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12">
                        <h6 class="text-uppercase font-weight-bold">درباره ما</h6><br>
                        <p id="A1">سارا اسدالهی هستم.</p>
                        <p>دانشجوی دانشگاه نوشیروانی ، ترم6 ، رشته مهدسی کامپیوتر</p>
                        <p>پروژه مروبط به درس تحلیل و طراحی سیستم های نرم افزاری</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h6 class="text-uppercase font-weight-bold">ارتباط</h6>
                    <p>
                    <br><a href="mailto:sara.jkm81@gmail.com?subject=Hello" target="_blank">ایمیل</a>
                    <br/><a href="tel:+123456789">شماره تماس</a>
                    <br/></p>
                </div>
            <div>
            <div class="footer-copyright text-center">خرداد ماه سال 1401</div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script src="main.js"></script>
    </body>
	
</html>

articles2/templates/articles2/babol.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>بابل</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        
        
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	</head>

    <body>
        <nav class="navbar navbar-expand-md">
            <a class="navbar-brand" href="{%url 'accounts:login'%}" target="_blank">ورود</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'home'%}" target="_blank">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#A1">درباره ما</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:signup'%}" target="_blank">عضویت</a>
                    </li>
                </ul>
            </div>
        </nav>


        <header class="page-header header container-fluid">
            <div class="description">
                
                <h3>شهرستان زیبای بابل</h3>
                <p>یکی از شهرهای استان مازندران که توانسته عده زیادی از افراد را درطول سال به خود جذب کند، بابل می باشد. این شهر به شهر بهارنارنج معروف می باشد و از جمله پر جمعیت ترین شهر های مازندران به حساب می آید.
                </p>
            </div>
        </header>

        
        {% for article in articles2 %}
        <div class="container featuresamol">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <h3 class="featureamol-title">{{article.title}}</h3>
                    <img src="{{article.image.url}}" class="img-fluid">
                    
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <br>
                    <br>
                    <p>{{article.snippet}}</p>
                    
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <div class="container">
            <a class="like"><i class="fa fa-thumbs-o-up"></i>  
                پسندیدم <input class="qty1" name="qty1" readonly="readonly" type="text" value="0" />
            </a>
            <a class="dislike"><i class="fa fa-thumbs-o-down"></i> 
                نپسندیدم <input class="qty2"  name="qty2" readonly="readonly" type="text" value="0" />
            </a>
        </div><br>

        
        {% endfor %}

        <div class="forms">
            <h4>نظر خود را راجع به این جاذبه ها ثبت کنید</h4>
            <form>
                <div class="form-group">
                  <label for="uname">نام :</label>
                  <input type="text" class="form-control" id="uname" placeholder="نام">
                </div>
    
                <div class="form-group">
                  <label for="exampleInputEmail1">ایمیل :</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل">
                </div>

                <div class="nform-group">
                    <label for="uname">نظر :</label>
                    <input type="text" class="form-control" id="uname" placeholder="نظر">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">ثبت نظر</button>
              </form><br>
        </div>

        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12">
                        <h6 class="text-uppercase font-weight-bold">درباره ما</h6><br>
                        <p id="A1">سارا اسدالهی هستم.</p>
                        <p>دانشجوی دانشگاه نوشیروانی ، ترم 6 ، رشته مهدسی کامپیوتر</p>
                        <p>پروژه مروبط به درس تحلیل و طراحی سیستم های نرم افزاری</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h6 class="text-uppercase font-weight-bold">ارتباط</h6>
                    <p>
                    <br><a href="mailto:sara.jkm81@gmail.com?subject=Hello" target="_blank">ایمیل</a>
                    <br/><a href="tel:+123456789">شماره تماس</a>
                    <br/></p>
                </div>
            <div>
            <div class="footer-copyright text-center">خرداد ماه سال 1401</div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script src="main.js"></script>
    </body>
</html>

articles3/templates/articles3/sari.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>ساری</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	</head>

    <body>
        <nav class="navbar navbar-expand-md">
            <a class="navbar-brand" href="{%url 'accounts:login'%}" target="_blank">ورود</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'home'%}" target="_blank">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#A1">درباره ما</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:signup'%}" target="_blank">عضویت</a>
                    </li>
                </ul>
            </div>
        </nav>


        <header class="page-header header container-fluid">
            <div class="description">
                
                <h3>شهرستان زیبای ساری</h3>
                <p>شهر ساری یک از مهم‌ترین شهرهای استان مازندران است که برای همه افراد شناخته شده است. در این شهر می‌توانید به گردش و تفریح پرداخته و اوقات خوشی را سپری کنید. در ضمن شهر ساری برای سرمایه‌گذاری نیز یک گزینه مطلوب قلمداد می‌گردد. از آنجایی که امکانات رفاهی و تغریحی ساری زیاد است بدین ترتیب برای تفریح یک شهر جذاب قلمداد می‌گردد. این شهر پرجمعیت در بین بسیاری از شهرهای شمالی طرفداران زیادی دارد. 

                    جاذبه‌های دیدنی ساری مسافران و گردشگران زیادی را هر ساله به سوی خود جذب می‌کند. این شهر دارای تاریخچه مخصوص به خود است که در قسمت‌های مختلف شهر می‌توان آثاری را در این رابطه مشاهده نمود. ساری دارای زیبایی‌های شگفت‌انگیزی است که توانسته علاقمندان زیادی را به خود وفادار نگه دارد. رودخانه و کوه و عمارت‌های خاص این شهر در نوع خود بی‌نظیر هستند. 
                </p>
            </div>
        </header>

        
        {% for article in articles3 %}
        <div class="container featuresamol">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <h3 class="featureamol-title">{{article.title}}</h3>
                    <img src="{{article.image.url}}" class="img-fluid">
                    
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <br>
                    <br>
                    <p>{{article.snippet}}</p>
                    <p>{{article.date}}</p>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <div class="container">
            <a class="like"><i class="fa fa-thumbs-o-up"></i>  
                پسندیدم <input class="qty1" name="qty1" readonly="readonly" type="text" value="0" />
            </a>
            <a class="dislike"><i class="fa fa-thumbs-o-down"></i> 
                نپسندیدم <input class="qty2"  name="qty2" readonly="readonly" type="text" value="0" />
            </a>
        </div><br>
        
        
        {% endfor %}
        
        <div class="forms">
            <h4>نظر خود را راجع به این جاذبه ها ثبت کنید</h4>
            <form>
                <div class="form-group">
                  <label for="uname">نام :</label>
                  <input type="text" class="form-control" id="uname" placeholder="نام">
                </div>
    
                <div class="form-group">
                  <label for="exampleInputEmail1">ایمیل :</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل">
                </div>

                <div class="nform-group">
                    <label for="uname">نظر :</label>
                    <input type="text" class="form-control" id="uname" placeholder="نظر">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">ثبت نظر</button>
              </form><br>
        </div>

        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12">
                        <h6 class="text-uppercase font-weight-bold">درباره ما</h6><br>
                        <p id="A1">سارا اسدالهی هستم.</p>
                        <p>دانشجوی دانشگاه نوشیروانی ، ترم6 ، رشته مهدسی کامپیوتر</p>
                        <p>پروژه مروبط به درس تحلیل و طراحی سیستم های نرم افزاری</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h6 class="text-uppercase font-weight-bold">ارتباط</h6>
                    <p>
                    <br><a href="mailto:sara.jkm81@gmail.com?subject=Hello" target="_blank">ایمیل</a>
                    <br/><a href="tel:+123456789">شماره تماس</a>
                    <br/></p>
                </div>
            <div>
            <div class="footer-copyright text-center">خرداد ماه سال 1401</div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script src="main.js"></script>
    </body>
</html>

templates/Home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> مازندران</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        
        <link rel="stylesheet" href="{% static 'style.css' %}">
	</head>
    
	<body>
        <!-- bootstrap -->
        <nav class="navbar navbar-expand-md">
            <a class="navbar-brand" href="{%url 'accounts:signup'%}" target="_blank">ورود</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'home'%}" target="_blank">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#A1">درباره ما</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:signup'%}" target="_blank">عضویت</a>
                    </li>
                </ul>
            </div>
        </nav>

        <header class="page-header header container-fluid">

            <div class="description">
                
                <h2>به سایت استان مازندران خوش آمدید!</h2><br>
                <p>مازندران نیاز به معرفی و تعریف ندارد. طبیعت بکر و زیبا، آب‌وهوای ملایم، دسترسی جاده‌ای مناسب و مردم مهربان و مهمان‌نواز، این استان بی‌نظیر را به انتخاب اول ایرانیان تبدیل کرده‌ است.<br>
                در اینجا با سه شهر معروف این استان آشنا می شویم.</p>
                
            </div>

        </header>
        
        
        <div class="container features">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12" id="B1">
                    <h3 class="feature-title">آمل</h3>
                    <a href="{%url 'articles:list'%}" target="_blank"><img src="amol.jpg" class="card-img-top rounded-circle"></a>
                    <p>برای دیدن مناظر شهر آمل کلیک کنید.</p>
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h3 class="feature-title">بابل</h3>
                    <a href="{%url 'articles2:listt'%}" target="_blank"><img src="babol.jpg" class="card-img-top rounded-circle"></a>
                    <p>برای دیدن مناظر شهر بابل کلیک کنید.</p>
                </div>
                <br>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h3 class="feature-title">ساری</h3>
                    <a href="{%url 'articles3:listtt'%}" target="_blank"><img src="sari.jpg" class="card-img-top rounded-circle"></a>
                    <p>برای دیدن مناظر شهر ساری کلیک کنید.</p>
                </div>


                <div class="col-lg-4 col-md-4 col-sm-12">
                
                </div>
            </div>
        </div>


        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12">
                        <h6 class="text-uppercase font-weight-bold">درباره ما</h6><br>
                        <p id="A1"> سارا اسدالهی هستم.</p>
                        <p>دانشجوی دانشگاه نوشیروانی ، ترم 6 ، رشته مهدسی کامپیوتر</p>
                        <p>پروژه مروبط به درس تحلیل و طراحی سیستم های نرم افزاری</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <h6 class="text-uppercase font-weight-bold">ارتباط</h6>
                    <p>
                    <br><a href="mailto:sara.jkm81@gmail.com?subject=Hello" target="_blank">ایمیل</a>
                    <br/><a href="tel:+123456789">شماره تماس</a>
                    <br/></p>
                </div>
            <div>
            <div class="footer-copyright text-center">خرداد ماه سال 1401</div>
        </footer>

        
        


        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script src="main.js"></script>
    </body>
	
</html>